-- Phase 1.5: 立ち回りと能力（武勇・知略・統率・徳望）

ALTER TABLE characters ADD COLUMN archetype_id TEXT NOT NULL DEFAULT 'domestic';
ALTER TABLE characters ADD COLUMN buyu INTEGER NOT NULL DEFAULT 40;
ALTER TABLE characters ADD COLUMN chiryaku INTEGER NOT NULL DEFAULT 40;
ALTER TABLE characters ADD COLUMN toso INTEGER NOT NULL DEFAULT 40;
ALTER TABLE characters ADD COLUMN tokubo INTEGER NOT NULL DEFAULT 40;
